/*
 * This source file was generated by the Gradle 'init' task
 */
package com;

import com.welvia.incomes.Application;
import org.junit.jupiter.api.Test;

class ApplicationTest {
    @Test void appHasAGreeting() {
        Application classUnderTest = new Application();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
